# Generated by Django 4.2.11 on 2026-03-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryagent',
            name='is_simulated',
            field=models.BooleanField(default=False),
        ),
    ]
