# Generated by Django 4.2.11 on 2026-04-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_deliveryagent_battery_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryagent',
            name='is_permanent',
            field=models.BooleanField(default=False),
        ),
    ]
