# Generated by Django 4.2.11 on 2026-03-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_lat', models.FloatField(blank=True, null=True)),
                ('current_lng', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('offline', 'Offline')], default='offline', max_length=20)),
                ('fatigue_score', models.FloatField(default=0.0)),
                ('total_km_today', models.FloatField(default=0.0)),
                ('orders_last_4hrs', models.IntegerField(default=0)),
                ('hours_active', models.FloatField(default=0.0)),
            ],
        ),
    ]
