# Generated by Django 4.2.11 on 2026-04-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_deliveryagent_is_simulated'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryagent',
            name='current_speed',
            field=models.FloatField(default=0.0),
        ),
    ]
