# Generated by Django 4.2.11 on 2026-04-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_deliveryagent_current_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryagent',
            name='battery_level',
            field=models.FloatField(default=100.0),
        ),
    ]
