# Generated by Django 4.2.11 on 2026-03-28 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('speed_kmph', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_updates', to='agents.deliveryagent')),
            ],
            options={
                'indexes': [models.Index(fields=['agent', '-timestamp'], name='tracking_lo_agent_i_f9b3f1_idx')],
            },
        ),
    ]
