# Generated by Django 4.2.11 on 2026-03-28 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(choices=[('speed_anomaly', 'Speed Anomaly'), ('agent_stuck', 'Agent Stuck'), ('route_deviation', 'Route Deviation'), ('unreachable', 'Unreachable')], max_length=50)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='agents.deliveryagent')),
            ],
        ),
    ]
